### ISSUE TITLE
Missing abs()

### ISSUE THREAD

**Issue by xianingz** [churchill-lab/scRATE#1]
Thanks for the tool!
I think the abs() at the following line should be before `loo_results`, is that correct?
https://github.com/churchill-lab/scRATE/blob/a870e8ae56c74840e127a6b5e05ce816984f85d3/R/select_model.R#L24

**Comment by xianingz** [comment]
Could you also help me with another question? Since the ZINB model is more flexible than NB model, I think the results for ZINB will always be equal or better than the NB model right? Then why do I sometimes get a lower elpd in ZINB than NB. Thanks!

**Comment by kbchoi-jax** [comment]
In posterior predictive check, a more flexible model does not necessarily perform better when it overfits. Take a look at [this](https://stats.stackexchange.com/questions/115157/what-are-posterior-predictive-checks-and-what-makes-them-useful) if you have a chance.

**Comment by xianingz** [comment]
Thanks for your quick response! This is very helpful.
How about the first question on the abs() ? I think this led to a wrong model selection in my dataset.

**Comment by kbchoi-jax** [comment]
It may lead to a simpler model than your original simulation if the simpler model performs pretty well with respect to posterior predictive check measure. Try smaller ‘margin’ values like 1. The default value of 2 is pretty stringent for more complex models to be selected. We needed to be stringent to show droplet scRNA-seq data IS zero inflated. Hope this help.

**Comment by xianingz** [comment]
Thanks but what I mean is that according to what you described in your method and your code in other parts, I think you may have accidentally put abs() in the wrong place in the code. I checked your code history, this potential bug happened when you add the code of `'P' %in% models`. The abs() should be on the `loo_results` rather than the whole thing including `'P' %in% models`. Otherwise, the left side of the `<` will always be 1 and this comparison would be not meaningful at al.

**Comment by xianingz** [comment]
In the same script, just compare the Line 24 with Line 30 and Line 38. They should be the same, right?

**Comment by kbchoi-jax** [comment]
Oh I see what you mean now. I will fix it soon. Thanks for checking!

**Comment by kbchoi-jax** [comment]
Fixed! Thanks again.
