### ISSUE TITLE
NB models generate NAs for median and MAD_SD

### ISSUE THREAD

**Issue by xianingz** [churchill-lab/scRATE#2]
Occasionally, I got NAs for the median and MAD_SD for NB models. Other models seems all fine. Does this mean the algorithm is not converged? I set the offset to be all zeros to purposely not control the differences in depth of coverage just as an experiment to fit the model with original values directly. Does this affect the estimation? Should I set it to another uniform values for this purpose? Thanks!

**Comment by kbchoi-jax** [comment]
I guess the model fitting was not successfully completed (perhaps because of offset values you are testing)?
